openapi: 3.0.0
info:
  title: Subscriptions API
  description: >
    The Subscriptions API allows other departments to:
      * create subscription records.
      * update specific parts of the subscription records.
      * retrieve:
          * subscription records
          * events 
          * possible state transitions
  version: 0.1.0

servers:
  - url: https://dev-api-ops-subscriptions-thesis.leanderpeter.de
    description: Development server
  - url: https://api-ops-subscriptions-thesis.leanderpeter.de
    description: Production server

tags:
  - name: Create
  - name: Update
  - name: Retrieve

security:
  - ApiKeyAuth: []
  - Actor: []

paths:
  /subscriptions:
    post:
      tags:
        - Create
      summary: Create a subscription
      description: Creates a subscription record.
      operationId: createSubscription
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSubscription"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OneSubscription"

    get:
      tags:
        - Retrieve
      summary: List all subscriptions
      description: >
        Returns subscription records.
      operationId: getSubscriptions
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
        - in: query
          name: count
          schema:
            type: integer
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: car_id
          schema:
            type: string
        - in: query
          name: state
          schema:
            type: string
            enum:
              ["CREATED", "ACTIVE", "CANCELED", "INACTIVE", "STOPPED", "ENDED"]
        - in: query
          name: type
          schema:
            type: string
            enum:
              ["B2B", "B2C", "MINIB2B"]
        - in: query
          name: contact_id
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllSubscriptions"


  /subscriptions/{subscription_id}:
    get:
      tags:
        - Retrieve
      summary: Retrieve a subscription
      description: >
        Returns a subscription record by ID.
      operationId: getSubscription
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
        - in: path
          name: subscription_id
          schema:
            type: string
          required: true
          description: Subscription ID
        - in: query
          name: expand
          schema:
            type: string
            enum:
              ["deposit", "contact"]
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OneSubscription"


  /subscriptions/{subscription_id}/state_transitions:
    get:
      tags:
        - Retrieve
      summary: List possible state transitions for a subscription
      description: >
        Returns possible state transitions for specific subscription record.
      operationId: possibleStateTransitions
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
        - in: path
          name: subscription_id
          schema:
            type: string
          required: true
          description: Subscription ID
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PossibleStateTransitions"

  /subscriptions/{subscription_id}/events:
    get:
      tags:
        - Retrieve
      summary: List events for a subscription
      description: >
        Returns events for a specific subscription record.
      operationId: subscriptionEvents
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
        - in: path
          name: subscription_id
          schema:
            type: string
          required: true
          description: Subscription ID
        - in: query
          name: from
          schema:
            type: string
            format: date-time
          description: Filter events from a given date and time
        - in: query
          name: to
          schema:
            type: string
            format: date-time
          description: Filter events till a given date and time
        - in: query
          name: count
          schema:
            type: number
          description: Number of events you want to fetch
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
          description: Allows you to sort by time of the event
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"
              
  /subscriptions/{subscription_id}/state:
    put:
      tags:
        - Update
      summary: Changes the state of a subscription
      description: Updates the state of a subscription.
      operationId: updateSubscriptionState
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSubscriptionState"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OneSubscription"


  /events:
    get:
      tags:
        - Retrieve
      summary: List events
      description: >
        Returns all events
      operationId: listEvents
      parameters:
        - in: header
          name: x-request-id
          schema:
            $ref: "#/components/schemas/x-request-id"
        - in: query
          name: from
          schema:
            type: string
            format: date-time
          description: Filter events from a given date and time
        - in: query
          name: to
          schema:
            type: string
            format: date-time
          description: Filter events till a given date and time
        - in: query
          name: count
          schema:
            type: number
          description: Number of events you want to fetch
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
          description: Allows you to sort by time of the event
        - in: query
          name: name
          schema:
            type: string
            enum:
              [
                subscription_created,
                subscription_canceled,
                subscription_activated,
              ]
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-Api-Key
      in: header
      description: Generated through the API Gateway console. Each service uses the separate key.

    Actor:
      type: apiKey
      name: x-actor
      in: header
      description: Identifies who has made the request.

  schemas:
    #Headers

    x-request-id:
      type: string
      description: Allows to trace the request.

    #Request body

    CreateSubscription:
      type: object
      properties:
        id:
          type: string
          description: Desired ID, pass only if you want same subscription ID across multiple systems, such as HubSpot
        car_reservation_token:
          type: string
          description: Car reservation token
        contact_id:
          type: string
          description: Contact ID
        type:
          type: string
          enum: [B2C, B2B, MINIB2B]
          description: Subscription type.
        signing_date:
          type: string
          format: date-time
          description: Contract signing date
        term:
          type: integer
          description: Subscription period
        term_type:
          type: string
          enum: [fixed, open_ended]
          description: Contract term type
        amount:
          type: integer
          description: Subscription fee in cents
        mileage_package:
          type: integer
        mileage_package_fee:
          type: integer
          description: Mileage package fee in cents
        additional_mileage_fee:
          type: integer
          description: Additional mileage fee fee in cents
        deposit:
          type: integer
          description: Deposit in cents
        handover_firstname:
          type: string
          description: First name of the recipient
        handover_lastname:
          type: string
          description: Last name of the recipient
        handover_housenumber:
          type: string
          description: Housenumber of the recipient
        handover_street:
          type: string
          description: Street name of the recipient
        handover_city:
          type: string
          description: City of of the recipient
        handover_zip:
          type: string
          description: Zipcode of the recipient
        handover_address_extra:
          type: string
          description: Any additional address data of the recipient
        preferred_handover_date:
          type: string
          format: date-time
          description: Preferred handover date and time by the customer
        handover_phone_number:
          type: string
          description: Phone number of the car handover recipient
      required:
        - car_reservation_token
        - contact_id
        - type
        - signing_date
        - term
        - amount
        - mileage_package
        - mileage_package_fee
        - additional_mileage_fee
        - deposit
        - handover_firstname
        - handover_lastname
        - handover_housenumber
        - handover_street
        - handover_city
        - handover_zip

    UpdateSubscriptionState:
      type: object
      properties:
        state:
          type: string
          enum:
            ["ACTIVE", "CANCELED", "INACTIVE", "STOPPED", "ENDED"]
        termination_reason: 
          type: string
          description: Reason of termination
        termination_date: 
          type: string
          description: Termination datetime in ISO_8601 format
          format: date-time
      required:
        - state


    #Responses

    200:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            id:
              type: string


    Events:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              subscription_id:
                type: integer
              name:
                type: string
              actor:
                type: string
              time:
                type: string
                format: date-time
              notes:
                type: string
              snapshot:
                $ref: "#/components/schemas/Subscription"
              
    PossibleStateTransitions:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: string



    Subscription:
      type: object
      required:
        - id
        - state
        - car_id
        - contact_id
        - type
        - signing_date
        - term
        - term_type
        - amount
        - mileage_package
        - mileage_package_fee
        - additional_mileage_fee
        - deposit
        - handover_firstname
        - handover_lastname
        - handover_housenumber
        - handover_street
        - handover_city
        - handover_zip
        - preferred_handover_date
        - handover_phone_number
        - created_at
        - updated_at
        - last_contract_change_date
      properties:
        id:
          type: string
          description: Subscription ID
        state:
          type: string
          enum:
            ["CREATED", "ACTIVE", "CANCELED", "INACTIVE", "STOPPED", "ENDED"]
        car_id:
          type: string
          description: ID of the car that was matched with this subscription
        contact_id:
          type: string
          description: Contact ID
        type:
          type: string
          enum: [B2C, B2B, MINIB2B]
          description: Customer type.
        signing_date:
          type: string
          format: date-time
          description: Contract signing date
        end_date:
          type: string
          format: date-time
          description: Contract end date
        term:
          type: integer
          description: Subscription period
        term_type:
          type: string
          enum: [fixed, open_ended]
          description: Contract term type
        amount:
          type: integer
          description: Subscription fee in cents
        mileage_package:
          type: integer
        mileage_package_fee:
          type: integer
          description: mileage package fee in cents
        additional_mileage_fee:
          type: integer
          description: additional mileage fee in cents
        deposit:
          type: integer
          description: deposit fee in cents
        handover_firstname:
          type: string
          description: First name of the recipient
        handover_lastname:
          type: string
          description: Last name of the recipient
        handover_housenumber:
          type: string
          description: Housenumber of the recipient
        handover_street:
          type: string
          description: Street name of the recipient
        handover_city:
          type: string
          description: City of of the recipient
        handover_zip:
          type: string
          description: Zipcode of the recipient
        handover_address_extra:
          type: string
          description: Any additional address data of the recipient
        preferred_handover_date:
          type: string
          format: date-time
          description: Preferred handover date and time by the customer
        actual_handover_date:
          type: string
          format: date-time
          description: Actual handover date and time
        handover_phone_number:
          type: string
          description: Phone number of the car handover recipient
        termination_reason: 
          type: string
          description: Reason of termination
        termination_date: 
          type: string
          description: Termination datetime in ISO_8601 format
          format: date-time
        created_at:
          type: string
          format: date-time
          description: Time at which subscription was created
        updated_at:
          type: string
          format: date-time
          description: Time at which subscription was last updated

    AllSubscriptions:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Subscription"

    OneSubscription:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Subscription"

    EmptyResponse:
      type: object
      properties:
        message:
          type: string
