name: Deployment-CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14-alpine3.16
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --ignore-scripts
    - name: Lint
      run: yarn lint
    - name: Test
      run: CI_TESTING=true yarn test-ci
      env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
    - name: Collect test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: junit.xml, coverage/cobertura-coverage.xml

  deploy-development:
    environment: DEV
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --ignore-scripts
    - name: Deploy
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "Deploying version ${VERSION}"
        npx sls create_domain --stage development --verbose
        npx sls deploy --stage development --verbose
      env:
        CORRELATION_ID_HEADER_NAME: ${{vars.CORRELATION_ID_HEADER_NAME}}
        ACTOR_HEADER_NAME: ${{vars.ACTOR_HEADER_NAME}}
        LOG_LEVEL: ${{vars.LOG_LEVEL}}
        SUBSCRIPTIONS_DATABASE_URL: ${{vars.SUBSCRIPTIONS_DATABASE_URL}}
        CARS_SERVICE_BASE_URL: ${{vars.CARS_SERVICE_BASE_URL}}
        CARS_SERVICE_API_KEY: ${{vars.CARS_SERVICE_API_KEY}}
        CUSTOMERS_SERVICE_BASE_URL: ${{vars.CUSTOMERS_SERVICE_BASE_URL}}
        CUSTOMERS_SERVICE_API_KEY: ${{vars.CUSTOMERS_SERVICE_API_KEY}}
        SUBSCRIPTIONS_DOMAIN: ${{vars.SUBSCRIPTIONS_DOMAIN}}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/${CI_DEFAULT_BRANCH}'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --ignore-scripts
    - name: Deploy
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "Deploying version ${VERSION}"
        npx sls create_domain --stage staging --verbose
        npx sls deploy --stage staging --verbose
      env:
        CORRELATION_ID_HEADER_NAME: ${{vars.CORRELATION_ID_HEADER_NAME}}
        ACTOR_HEADER_NAME: ${{vars.ACTOR_HEADER_NAME}}
        LOG_LEVEL: ${{vars.LOG_LEVEL}}
        SUBSCRIPTIONS_DATABASE_URL: ${{vars.SUBSCRIPTIONS_DATABASE_URL}}
        CARS_SERVICE_BASE_URL: ${{vars.CARS_SERVICE_BASE_URL}}
        CARS_SERVICE_API_KEY: ${{vars.CARS_SERVICE_API_KEY}}
        CUSTOMERS_SERVICE_BASE_URL: ${{vars.CUSTOMERS_SERVICE_BASE_URL}}
        CUSTOMERS_SERVICE_API_KEY: ${{vars.CUSTOMERS_SERVICE_API_KEY}}
        SUBSCRIPTIONS_DOMAIN: ${{vars.SUBSCRIPTIONS_DOMAIN}}

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --ignore-scripts
    - name: Deploy
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "Deploying version ${VERSION}"
        npx sls create_domain --stage production --verbose
        npx sls deploy --stage production --verbose
      env:
        CORRELATION_ID_HEADER_NAME: ${{vars.CORRELATION_ID_HEADER_NAME}}
        ACTOR_HEADER_NAME: ${{vars.ACTOR_HEADER_NAME}}
        LOG_LEVEL: ${{vars.LOG_LEVEL}}
        SUBSCRIPTIONS_DATABASE_URL: ${{vars.SUBSCRIPTIONS_DATABASE_URL}}
        CARS_SERVICE_BASE_URL: ${{vars.CARS_SERVICE_BASE_URL}}
        CARS_SERVICE_API_KEY: ${{vars.CARS_SERVICE_API_KEY}}
        CUSTOMERS_SERVICE_BASE_URL: ${{vars.CUSTOMERS_SERVICE_BASE_URL}}
        CUSTOMERS_SERVICE_API_KEY: ${{vars.CUSTOMERS_SERVICE_API_KEY}}
        SUBSCRIPTIONS_DOMAIN: ${{vars.SUBSCRIPTIONS_DOMAIN}}
  
  db-migrate-dev:
    runs-on: ubuntu-latest
    needs: deploy-development
    if: github.event_name == 'pull_request'
    steps:
    - name: Migrate
      run: aws lambda invoke --region eu-central-1 --function-name subscriptions-development-db-migrate response.json
  db-migrate-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/${CI_DEFAULT_BRANCH}'
    steps:
    - name: Migrate
      run: aws lambda invoke --region eu-central-1 --function-name subscriptions-staging-db-migrate response.json
  db-migrate-production:
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Migrate
      run: aws lambda invoke --region eu-central-1 --function-name subscriptions-production-db-migrate response.json
